### ISSUE TITLE
joomla

### ISSUE THREAD

**Issue by BatLev** [tomlinsonk/site-graph#19]
Hello Dear Sir!

I am trying to use you software (its prety cool by the way) but it seems to have a problem with joomla where the links containt article id-s and all subpage is basicly baseurl/index.php...id=654. what can i change or do to make it visualize my entire site including this type of links?

**Comment by BatLev** [comment]
i commented out the defragmentation section and it works well. thank you for the program. in the process i made an evermoving monster as representation but maybe the site was too big

**Comment by tomlinsonk** [comment]
Glad you found a fix! We could add a command line option for this
