### ISSUE TITLE
Errors with accents or emojis in url?

### ISSUE THREAD

**Issue by Julianoe** [tomlinsonk/site-graph#21]
Urls like `https://example.com/tags/🌳arbré` are valid in a browser. It would be interpreted like this `https://example.com/tags/%F0%9F%8C%B3arbr%C3%A9/`

It seems like the script does not do the interpretation work and throws error instead.
Are you aware of this? Is it fixable?

**Comment by tomlinsonk** [comment]
Good catch! I'll try to fix this

**Comment by tomlinsonk** [comment]
After some experimentation, it looks to me like the script is handling the URL just fine (I tried a different webpage with emoji URLs and it worked). For some reason, that example.com page is deciding to send a 404 response to the python `requests` request... Maybe it doesn't want to be crawled?

Specifically, I'm consistently getting a 404 response when I do: `requests.head('https://example.com/tags/🌳arbré')` or `requests.head('https://example.com/tags/%F0%9F%8C%B3arbr%C3%A9/')`.

**Comment by Julianoe** [comment]
I used example.com as a convention, I can't disclose the website I was trying to crawl on a public thread.
I can contact you in private if you need more logs or something.

**Comment by tomlinsonk** [comment]
I think there might be some other issue unrelated to the accented characters and emoji. As far as I can tell, the script handles these correctly. For instance, I can successfully start a crawl on these URLs:
- https://de.wikipedia.org/wiki/FC_Bayern_München
- https://techmighty.in/❤-emoji-use-in-domain-name-or-urls-of-website-❤/
