### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by marcoXbresciani** [tomlinsonk/site-graph#22]
Hello,
  by executing the installation and configuration as described:
```
git clone https://github.com/tomlinsonk/site-graph.git
cd site-graph
pip3 install -r requirements.txt
```
everything seems working fine.
Then, trying to crawl the website from inside the `site_graph` folder

```
python3 site_graph.py https://marcoXbresciani.codeberg.page
```

I see this error:

```
Traceback (most recent call last):
  File "C:\Users\marco.bresciani\Chiavetta\Software\site-graph\site_graph.py", line 2, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

I've tried by `pip3 install bs4` but no luck.

* Python 3.9.12
* pip 23.2.1 from C:\Python39\lib\site-packages\pip (python 3.9)

**Comment by marcoXbresciani** [comment]
Dependencies seems fine, as far as I can see.
```
C:\Users\marco.bresciani\Chiavetta\Software\site-graph>pip3 install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in c:\python39\lib\site-packages (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\python39\lib\site-packages (from beautifulsoup4) (2.4.1)
```

```
C:\Users\marco.bresciani\Chiavetta\Software\site-graph>pip3 install bs4
Requirement already satisfied: bs4 in c:\python39\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\python39\lib\site-packages (from bs4) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\python39\lib\site-packages (from beautifulsoup4->bs4) (2.4.1)
```

**Comment by tomlinsonk** [comment]
Hi Marco! Unfortunately there are a bunch of possible reasons why Python isn't seeing your installed modules, so it's hard to know why it's happening in your case. Here are some places to look for possible fixes:
- https://stackoverflow.com/questions/14295680/unable-to-import-a-module-that-is-definitely-installed
- https://stackoverflow.com/questions/15052206/python-pip-install-module-is-not-found-how-to-link-python-to-pip-location
- https://realpython.com/lessons/why-cant-python-find-my-modules/

You could also try using virtualenv, which is designed to avoid these types of issues (brief tutorial: https://thepythonguru.com/python-virtualenv-guide/).

**Comment by marcoXbresciani** [comment]
Oky, I'll try, thanks!
