### ISSUE TITLE
function to_numpy_matrix() depreciated in recent networkx version

### ISSUE THREAD

**Issue by leodumont** [tomlinsonk/site-graph#23]
Hello,

The function `to_numpy_matrix() `called line 145 (see link below) to produce the adjency matrix is depreciated since networkx 3.0.

If changed to `to_numpy_array()` it works fine.

https://github.com/tomlinsonk/site-graph/blob/06b0ef38eb58781e20f94bde6cd71009824cdaa3/site_graph.py#L145C1-L145C70

**Comment by tomlinsonk** [comment]
Fixed! Thanks for pointing this out.
