### ISSUE TITLE
supporting local files

### ISSUE THREAD

**Issue by matkoniecz** [tomlinsonk/site-graph#4]
it be OK to make PR adding support for reading local files?

It would be useful for me as I am trying to make/find a decent tool for detecting broken links.

And possible additional feature: detect files that are within folder but are not linked (orphaned html file, not linked from any part of the website and/or unused media files)

(would be happy to make PR if that would be accepted and #3 is resoved)

**Comment by tomlinsonk** [comment]
Go for it! :)

**Comment by matkoniecz** [comment]
`sudo npm install http-server -g` BTW, is there way to install node modules without sudo and have it within PATH?

`http-server` in directory with html files

`p site_graph.py http://127.0.0.1:8080/ --visit-external --force`

is a promising workaround that would require no extra code. Though some external links returned 418 of all things ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418 ). But maybe it is case of "Some websites use this response for requests they do not wish to handle, such as automated queries." as noted in docs?

Idea of starting local server and running www link checker on it is from https://github.com/LukasHechenberger/broken-link-checker-local/

**Comment by tomlinsonk** [comment]
I'm not familiar with node, unfortunately. But this workaround seems good to me! Maybe we can add it to the README? Interesting re: the 418 errors... ignoring this is probably fine, unless you want to add another node indicator for "possible broken link, manual check required" or something

**Comment by matkoniecz** [comment]
For now my conclusion is that local file support requires no extra support from this tool. I prefer to not add `sudo npm` to readme as there must be a better way to achieve this and I want to avoid promoting random sudo everywhere.

**Comment by nathan-artist** [comment]
@matkoniecz I would recommend adding a note to the readme about npm's `http-server`. I was trying to figure out how I could modify this script to work with local files. Fortunately I quickly found this issue and the wonderfully easy no-code solution given here. It would have helped me if this information had been in the readme. Others probably could use this information as well. I may submit a PR to modify the readme.
